# Wrangler configuration for Cloudflare Pages
[build]
command = "cd clovalink && npm install && npm run build"
output_dir = "clovalink/out"

[site]
bucket = "clovalink/out"

[build.environment]
NODE_VERSION = "18.18.0" 